### ISSUE TITLE
Trademark Infringement

### ISSUE THREAD

**Issue by john-connor** [jack-fraser/crypto-currency-splash#1]
You may not use the term "Vcash" in relations to crypto-currencies without explicit permission as it is protected by international trademark laws. Vcash attorneys have sent DMCA to GitHub. Regards.

**Comment by jack-fraser** [comment]
will change. thanks for the heads up :D

**Comment by john-connor** [comment]
You never came to us with a plan on what you desired to do and ask for permission to use our trademark. You are still in violation "static simple site for a website detailing the vcash crypto currency". Next time you want to use our trademark bring us a proposal so our attorneys may review it otherwise your careless actions may result in a lawsuit against the Vcash project.
